version: "3.9"
services:
  php:
    build:
      context: ./docker/php # 後述
      dockerfile: Dockerfile
    volumes:
      - ./server:/var/www

  nginx:
    image: nginx:1.20-alpine
    ports:
      - 80:80
    volumes:
      - ./server:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www

  db:
    build:
      context: ./docker/db #後述
      dockerfile: Dockerfile
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/db/log:/var/log/mysql
    ports:
      - "4306:3306"

volumes:
  db-store: null
